[package]
name = "chef-builds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = { version = "0.2.31", features = ["rust_1_64"] }
path-lib = { version = "0.1.0", path = "path-lib" }
